exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("category")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("category").insert([
        {
          category_id: "0cc62b56-b8d9-4db0-b1e3-912b1a6c290e",
          category_name: "My Curious Nature",
          category_description: "Trivia game about science and nature.",
          category_url: "https://mycuriousnature.netlify.app/login.html",
          category_team_name: "Kevin Withrow",
          category_git: "https://github.com/KevinWithrow",
          category_cohort: "Houston-Flex-Jan-2020",
          category_languages: "JavaScript, React, SQL",
          category_picture: "kevinproject1.png",
          category_picture2: "kevinproject2.png",
          category_picture3: null,
          category_picture4: null,
          category_picture5: null,
          category_picture6: null,
          category_picture7: null,
          category_picture8: null,
          category_javascript: "Javascript",
          category_react: null,
          category_html: "HTML",
          category_css: "CSS",
          category_python: null,
          category_node: "Node",
          category_express: "Express",
          category_json: null,
          category_rest: null,
          category_sql: "SQL",
          category_cloud: "Cloud",
          category_memberone: "Kevin Withrow",
          category_oneemail: "kevin.withrow83@gmail.com",
          category_onegit: "https://github.com/KevinWithrow",
          category_onelinkedin: "https://www.linkedin.com/in/kevinwithrow",
          category_oneportfolio: "https://scottstringer.netlify.app",
          category_onetwitter: null,
          category_onepicture: "kevinprofile.jpg"
        },
        {
          category_id: "0cc62b56-b8d9-4db0-b1e3-912b1a6c190e",
          category_name: "My Warhammer Quest Project",
          category_description: "The purpose of the site is to be a random generator for the Monsters, Treasures and Events in a game of the tabletop adventure board game Warhammer Quest.",
          category_url: null,
          category_team_name: "Scott Stringer",
          category_git: "https://github.com/dmstringer/my-quest-project",
          category_cohort: "Houston-Flex-Jan-2020",
          category_languages: null,
          category_picture: "scottproject1.jpg",
          category_picture2: "scottproject2.jpg",
          category_picture3: "scottproject3.jpg",
          category_picture4: "scottproject4.jpg",
          category_picture5: null,
          category_picture6: null,
          category_picture7: null,
          category_picture8: null,
          category_javascript: null,
          category_react: "React",
          category_html: "HTML",
          category_css: "CSS",
          category_python: null,
          category_node: "Node",
          category_express: "Express",
          category_json: null,
          category_rest: null,
          category_sql: "SQL",
          category_cloud: "Cloud",
          category_memberone: "Scott Stringer",
          category_oneemail: "scottstringer@gmail.com",
          category_onegit: "https://github.com/dmstringer",
          category_onelinkedin: "https://www.linkedin.com/in/scott-thomas-stringer",
          category_oneportfolio: "https://scottstringer.netlify.app",
          category_onetwitter: null,
          category_onepicture: "scottprofile.jpg"
        },
        {
          category_id: "0cc62b56-b8d9-3db0-b1e3-912b1a6c190e",
          category_name: "eyeRation",
          category_description: "This is an inventory application developed using the PERN stack. The eyeRation app keeps track of inventory items for daily use.",
          category_url: "https://www.eyeration.com",
          category_team_name: "Ulysses Salinas",
          category_git: null,
          category_cohort: "Houston-Flex-Jan-2020",
          category_languages: null,
          category_picture: "ulyproject1.jpg",
          category_picture2: "ulyproject2.jpg",
          category_picture3: "ulyproject3.jpg",
          category_picture4: "ulyproject4.jpg",
          category_picture5: null,
          category_picture6: null,
          category_picture7: null,
          category_picture8: null,
          category_javascript: null,
          category_react: "React",
          category_html: "HTML",
          category_css: "CSS",
          category_python: null,
          category_node: "Node",
          category_express: "Express",
          category_json: null,
          category_rest: null,
          category_sql: "SQL",
          category_cloud: "Cloud",
          category_memberone: "Ulysses Salinas",
          category_oneemail: "ulysses.salinas88@gmail.com",
          category_onegit: "https://github.com/ulysses-salinas",
          category_onelinkedin: "https://www.linkedin.com/in/ulysses-salinas",
          category_oneportfolio: "https://www.ulyssessalinas.com",
          category_onetwitter: null,
          category_onepicture: "ulyprofile.jpg"
        },
        {
          category_id: "0cc52b56-b8d9-3db0-b1e3-912b1a6c190e",
          category_name: "Project Vault",
          category_description: "Project Vault is a market place for all DigitalCraft's developers to showcase their projects. The app allows users to search projects based on the technologies used and view each project's screenshots and social information.",
          category_url: "https://www.northrange.dev",
          category_team_name: "Matthew Alagala",
          category_git: "https://github.com/mattalagala/FinalProject",
          category_cohort: "Houston-Flex-Jan-2020",
          category_languages: null,
          category_picture: "mattproject1.jpg",
          category_picture2: "mattproject2.jpg",
          category_picture3: "mattproject3.jpg",
          category_picture4: "mattproject4.jpg",
          category_picture5: "mattproject5.jpg",
          category_picture6: "mattproject6.jpg",
          category_picture7: "mattproject7.jpg",
          category_picture8: "mattproject8.jpg",
          category_javascript: "Javascript",
          category_react: null,
          category_html: "HTML",
          category_css: "CSS",
          category_python: null,
          category_node: "Node",
          category_express: "Express",
          category_json: "JSON",
          category_rest: "REST",
          category_sql: "SQL",
          category_cloud: "Cloud",
          category_memberone: "Matthew Alagala",
          category_oneemail: "matthew.alagala@gmail.com",
          category_onegit: "https://github.com/mattalagala",
          category_onelinkedin: "https://www.linkedin.com/in/matthew-alagala",
          category_oneportfolio: "https://www.matthewalagala.com",
          category_onetwitter: null,
          category_onepicture: "mattprofile.png"
        },
        // {category_id: 2, category_name :'Acoustic Guitar', category_picture: 'https://picsum.photos/620/620'},
        // {category_id: 3, category_name :'Amplifier', category_picture: 'https://picsum.photos/620/620'},
        // {category_id: 4, category_name :'Bass', category_picture: 'https://picsum.photos/620/620'},
      ]);
    });
};

// id serial primary key,
// "category_name" text,
// "category_picture" text,
