exports.seed = function (knex) {
	// Deletes ALL existing entries
	return knex("teams")
		.del()
		.then(function () {
			// Seed division entries
			return knex("teams").insert([
				{
					team_id: 1,
					division_id: 4,
					team_name: "Kansas City Chiefs",
					wins: 14,
					losses: 2,
					ties: 0,
					division_rank: 1,
					league_rank: 1,
				},
				{
					team_id: 2,
					division_id: 2,
					team_name: "Buffalo Bills",
					wins: 13,
					losses: 3,
					ties: 0,
					division_rank: 1,
					league_rank: 2,
				},
				{
					team_id: 3,
					division_id: 5,
					team_name: "Green Bay Packers",
					wins: 13,
					losses: 3,
					ties: 0,
					division_rank: 1,
					league_rank: 3,
				},
				{
					team_id: 4,
					division_id: 7,
					team_name: "New Orleans Saints",
					wins: 12,
					losses: 4,
					ties: 0,
					division_rank: 1,
					league_rank: 4,
				},
				{
					team_id: 5,
					division_id: 1,
					team_name: "Pittsburgh Steelers",
					wins: 12,
					losses: 4,
					ties: 0,
					division_rank: 1,
					league_rank: 5,
				},
				{
					team_id: 6,
					division_id: 8,
					team_name: "Seattle Seahawks",
					wins: 12,
					losses: 4,
					ties: 0,
					division_rank: 1,
					league_rank: 6,
				},
				{
					team_id: 7,
					division_id: 1,
					team_name: "Baltimore Ravens",
					wins: 11,
					losses: 5,
					ties: 0,
					division_rank: 2,
					league_rank: 7,
				},
				{
					team_id: 8,
					division_id: 1,
					team_name: "Cleveland Browns",
					wins: 11,
					losses: 5,
					ties: 0,
					division_rank: 3,
					league_rank: 8,
				},
				{
					team_id: 9,
					division_id: 3,
					team_name: "Indianapolis Colts",
					wins: 11,
					losses: 5,
					ties: 0,
					division_rank: 2,
					league_rank: 9,
				},
				{
					team_id: 10,
					division_id: 7,
					team_name: "Tampa Bay Buccaneers",
					wins: 11,
					losses: 5,
					ties: 0,
					division_rank: 2,
					league_rank: 10,
				},
				{
					team_id: 11,
					division_id: 3,
					team_name: "Tennessee Titans",
					wins: 11,
					losses: 5,
					ties: 0,
					division_rank: 1,
					league_rank: 11,
				},
				{
					team_id: 12,
					division_id: 8,
					team_name: "Los Angeles Rams",
					wins: 10,
					losses: 6,
					ties: 0,
					division_rank: 2,
					league_rank: 12,
				},
				{
					team_id: 13,
					division_id: 2,
					team_name: "Miami Dolphins",
					wins: 10,
					losses: 6,
					ties: 0,
					division_rank: 2,
					league_rank: 13,
				},
				{
					team_id: 14,
					division_id: 8,
					team_name: "Arizona Cardinals",
					wins: 8,
					losses: 8,
					ties: 0,
					division_rank: 3,
					league_rank: 14,
				},
				{
					team_id: 15,
					division_id: 5,
					team_name: "Chicago Bears",
					wins: 8,
					losses: 8,
					ties: 0,
					division_rank: 2,
					league_rank: 15,
				},
				{
					team_id: 16,
					division_id: 4,
					team_name: "Las Vegas Rateam_iders",
					wins: 8,
					losses: 8,
					ties: 0,
					division_rank: 2,
					league_rank: 16,
				},
				{
					team_id: 17,
					division_id: 4,
					team_name: "Los Angeles Chargers",
					wins: 7,
					losses: 9,
					ties: 0,
					division_rank: 3,
					league_rank: 17,
				},
				{
					team_id: 18,
					division_id: 5,
					team_name: "Minnisota Vikings",
					wins: 7,
					losses: 9,
					ties: 0,
					division_rank: 3,
					league_rank: 18,
				},
				{
					team_id: 19,
					division_id: 2,
					team_name: "New England Patriots",
					wins: 7,
					losses: 9,
					ties: 0,
					division_rank: 3,
					league_rank: 19,
				},
				{
					team_id: 20,
					division_id: 6,
					team_name: "Washington Football Team",
					wins: 7,
					losses: 9,
					ties: 0,
					division_rank: 1,
					league_rank: 20,
				},
				{
					team_id: 21,
					division_id: 6,
					team_name: "Dallas Cowboys",
					wins: 6,
					losses: 10,
					ties: 0,
					division_rank: 3,
					league_rank: 21,
				},
				{
					team_id: 22,
					division_id: 6,
					team_name: "New York Giants",
					wins: 6,
					losses: 10,
					ties: 0,
					division_rank: 2,
					league_rank: 22,
				},
				{
					team_id: 23,
					division_id: 8,
					team_name: "San Francisco 49ers",
					wins: 6,
					losses: 10,
					ties: 0,
					division_rank: 4,
					league_rank: 23,
				},
				{
					team_id: 24,
					division_id: 7,
					team_name: "Carolina Panthers",
					wins: 5,
					losses: 11,
					ties: 0,
					division_rank: 3,
					league_rank: 24,
				},
				{
					team_id: 25,
					division_id: 4,
					team_name: "Denver Broncos",
					wins: 5,
					losses: 11,
					ties: 0,
					division_rank: 4,
					league_rank: 25,
				},
				{
					team_id: 26,
					division_id: 5,
					team_name: "Detroit Lions",
					wins: 5,
					losses: 11,
					ties: 0,
					division_rank: 4,
					league_rank: 26,
				},
				{
					team_id: 27,
					division_id: 1,
					team_name: "Cincinnati Bengals",
					wins: 4,
					losses: 11,
					ties: 1,
					division_rank: 4,
					league_rank: 27,
				},
				{
					team_id: 28,
					division_id: 6,
					team_name: "Philteam_idelphia Eagles",
					wins: 4,
					losses: 11,
					ties: 1,
					division_rank: 4,
					league_rank: 28,
				},
				{
					team_id: 29,
					division_id: 7,
					team_name: "Atlanta Falcons",
					wins: 4,
					losses: 12,
					ties: 0,
					division_rank: 4,
					league_rank: 29,
				},
				{
					team_id: 30,
					division_id: 3,
					team_name: "Houston Texans",
					wins: 4,
					losses: 12,
					ties: 0,
					division_rank: 3,
					league_rank: 30,
				},
				{
					team_id: 31,
					division_id: 2,
					team_name: "New York Jets",
					wins: 2,
					losses: 14,
					ties: 0,
					division_rank: 4,
					league_rank: 31,
				},
				{
					team_id: 32,
					division_id: 3,
					team_name: "Jacksonville Jaguars",
					wins: 1,
					losses: 15,
					ties: 0,
					division_rank: 4,
					league_rank: 32,
				},
			]);
		});
};
